### ISSUE TITLE
File.mkv "does not contain segmented chapters"

### ISSUE THREAD

**Issue by ghost** [hilts-vaughan/UnlinkMKV-GUI#1]

**Comment by hilts-vaughan** [comment]
Hi,

Can you post your log here? This is the right place. :) Also, your OS would help too.

**Comment by fuzzycobalt** [comment]
Log....? Sorry I am so bad at this...

**Comment by hilts-vaughan** [comment]
When you downloaded the program, you should have got a GUI tool along with the script. If you're running the GUI, the textbox that has this info:

UnlinkMKV
processing F:/Temporary/Episode 01.mkv
checking if file is segmented
"F:/Temporary/Episode 01.mkv" does not contain segmented chapters

in it is a "log". If you're confident it's linked,  you might want to check that you installed Perl and have ran `cpan Log::Log4perl` before the program.

**Comment by fuzzycobalt** [comment]
AH output log, yes one minute here...

UnlinkMKV
   removed tmp C:\Users\AppData\Local\Temp\76752
   created tmp C:\Users\AppData\Local\Temp\76752
   processing F:/Temporary/Another/Another 01.mkv
      checking if file is segmented
         sys > mkvextract chapters "F:/Temporary/Another/Another 01.mkv"
         "F:/Temporary/Another/Another 01.mkv" does not contain segmented chapters
      removed tmp C:\Users\AppData\Local\Temp\76752
      created tmp C:\Users\AppData\Local\Temp\76752
   removed tmp C:\Users\AppData\Local\Temp\76752 [exiting]

**Comment by hilts-vaughan** [comment]
See above. Ensure the logging module was installed by running that in a command prompt. If that fixes it, let me know. Otherwise, there may be a legitimate issue with that release in which I can fix.

**Comment by fuzzycobalt** [comment]
![log](https://cloud.githubusercontent.com/assets/12002472/7805394/dcc451d6-032e-11e5-8c28-8089ce91b2f9.png)

**Comment by hilts-vaughan** [comment]
It sounds like something with the file structure. Please attach a "verbose" log. Check off "verbose" before running the application and paste the log here.

**Comment by hilts-vaughan** [comment]
Sounds like something is wrong with that release or your copy of the tools are wrong. What happens if you run 'mkvextract' from the command line? Do you get any errors? If not, e-mail me at my Github profile and we'll get this resolved.

**Comment by fuzzycobalt** [comment]
One thing that I forgot to include, earlier today I was using this program to unlink a bunch of videos from a series, and it worked fine, except for one thing:

The beginning of the video was fine, then the previously ordered chapter opening played fine, and the core of the show played fine, but when the ending came up the video would stop, the audio and subs stopped, and everything in the playback froze until I closed VLC.

**Comment by fuzzycobalt** [comment]
oh, that might be it... I dont think I HAVE mkvextract. I have mkvtoolnix though.

"run 'mkvextract' from the command line" I wouldn't even know how to do this anyways.... Sorry :/

**Comment by hilts-vaughan** [comment]
From the command line just type:

`mkvextract` and paste the output. Simple as that. As for the freezing, try updating VLC or using MPC-HD. VLC has had some bugs with stuff like that but MPC-HD has been working fine, Plex etc and latest versions of VLC. If those still freeze, I'd love to know so I can fix it. Let me know! :)

Though, it sounds like your mkvextract is working if you did others. If you want me to see what's up with the file, feel free to e-mail me and I can fix the issue in the next day or two.

**Comment by fuzzycobalt** [comment]
which command line....? :/

**Comment by hilts-vaughan** [comment]
Your mkvextract is working fine per your other comment. No need to run it.

I'll need a copy of the file to see what's going on. Feel free to just
email me the original filename.

**Comment by fuzzycobalt** [comment]
Ok sounds good. Its really big though... 1.5 Gigs... Google drive it is then I guess.

**Comment by hilts-vaughan** [comment]
Drop me an email before uploading anything.

**Comment by fuzzycobalt** [comment]
Any luck since we last talked?

**Comment by CaptainJet** [comment]
This is almost definitely a PATH issue with mkvtoolnix. You need to run `mkvextract` in CMD, the same thing you had open here https://github.com/hilts-vaughan/UnlinkMKV-GUI/issues/1#issuecomment-105390432, and show us the output. UnlinkMKV-GUI's verbose output will show it attempting to run the command, but not if it failed or not.

**Comment by hilts-vaughan** [comment]
@fuzzycobalt What is your install path to MKVToolnix? It's possible it's not there and the auto detect code has failed, for some reason. The validator on run is supposed to detect these cases but maybe you installed a version incorrectly for your system architecture.

Try running as @CaptainJet had advised.

**Comment by hilts-vaughan** [comment]
This was fixed with a previous release. Feel free to try again.
