### ISSUE TITLE
Missing Segments

### ISSUE THREAD

**Issue by sherlockeb** [hilts-vaughan/UnlinkMKV-GUI#10]
I've tried several Coalgirls releases and I always get missing segments errors

UnlinkMKV
   removed tmp C:\Users\SEB\AppData\Local\Temp\4600
   created tmp C:\Users\SEB\AppData\Local\Temp\4600
   processing C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv"
         "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv" contains segmented chapters
      generating chapter file
         loading chapters
            Checking for editions...
            Ordered flag found and dropped
            Done checking for editions...
            [EXT]
    ChStart 00:00:00.000000000
    ChEnd   00:01:58.660000001
    Offset  00:01:58.660000001
    OffTE   00:01:58.660000001
            setting part [Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv => C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv
            Running on Windows; attempting to use symbolic link fallback for Windows
            sys > cmd /c mklink "C:\Users\SEB\AppData\Local\Temp\4600\parts[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv" "C:\Serial Experiments Lain[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv"
            [INT]
    ChStart 00:01:58.660000002
    ChEnd   00:22:17.336000002
    Offset  00:01:58.660000001
    OffTE   00:22:17.336000002
            [EXT]
    ChStart 00:22:17.336000002
    ChEnd   00:23:54.263000003
    Offset  00:03:35.587000002
    OffTE   00:23:54.263000003
         writing chapter temporary file
         looking for segment parts
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv"
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_ED_(1008x720_Blu-Ray_FLAC)_[2C54E6D8].mkv"
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_OP_(1008x720_Blu-Ray_FLAC)_[827F1AF5].mkv"
         checking that all required segments were found
         missing segment: 0x87 0xa4 0xc2 0x0d 0x94 0x45 0x40 0x23 0xa4 0x6f 0x92 0xe3 0x2f 0x02 0x1c 0x1a
         missing segment: 0xad 0x96 0xa7 0xb9 0x0d 0xc1 0x95 0x17 0xbc 0x4a 0x67 0x7f 0x5a 0xe7 0x39 0xb8
         missing segments!
         removed tmp C:\Users\SEB\AppData\Local\Temp\4600 [exiting]
UnlinkMKV
   removed tmp C:\Users\SEB\AppData\Local\Temp\4908
   created tmp C:\Users\SEB\AppData\Local\Temp\4908
   processing C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv"
         "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv" contains segmented chapters
      generating chapter file
         loading chapters
            Checking for editions...
            Ordered flag found and dropped
            Done checking for editions...
            [EXT]
    ChStart 00:00:00.000000000
    ChEnd   00:01:58.660000001
    Offset  00:01:58.660000001
    OffTE   00:01:58.660000001
            setting part [Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv => C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv
            Running on Windows; attempting to use symbolic link fallback for Windows
            sys > cmd /c mklink "C:\Users\SEB\AppData\Local\Temp\4908\parts[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv" "C:\Serial Experiments Lain[Coalgirls]_Serial_Experiments_Lain_02_(1008x720_Blu-Ray_FLAC)_[548EA5AC].mkv"
            [INT]
    ChStart 00:01:58.660000002
    ChEnd   00:22:14.583000002
    Offset  00:01:58.660000001
    OffTE   00:22:14.583000002
            [EXT]
    ChStart 00:22:14.583000002
    ChEnd   00:23:51.510000003
    Offset  00:03:35.587000002
    OffTE   00:23:51.510000003
         writing chapter temporary file
         looking for segment parts
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_01_(1008x720_Blu-Ray_FLAC)_[F0EF8AF8].mkv"
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_ED_(1008x720_Blu-Ray_FLAC)_[2C54E6D8].mkv"
            sys > mkvinfo "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_OP_(1008x720_Blu-Ray_FLAC)_[827F1AF5].mkv"
         checking that all required segments were found
         missing segment: 0x87 0xa4 0xc2 0x0d 0x94 0x45 0x40 0x23 0xa4 0x6f 0x92 0xe3 0x2f 0x02 0x1c 0x1a
         missing segment: 0xad 0x96 0xa7 0xb9 0x0d 0xc1 0x95 0x17 0xbc 0x4a 0x67 0x7f 0x5a 0xe7 0x39 0xb8
         missing segments!
         removed tmp C:\Users\SEB\AppData\Local\Temp\4908 [exiting]
UnlinkMKV
   removed tmp C:\Users\SEB\AppData\Local\Temp\4276
   created tmp C:\Users\SEB\AppData\Local\Temp\4276
   processing C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_ED_(1008x720_Blu-Ray_FLAC)_[2C54E6D8].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_ED_(1008x720_Blu-Ray_FLAC)_[2C54E6D8].mkv"
         "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_ED_(1008x720_Blu-Ray_FLAC)_[2C54E6D8].mkv" does not contain segmented chapters
      removed tmp C:\Users\SEB\AppData\Local\Temp\4276
      created tmp C:\Users\SEB\AppData\Local\Temp\4276
   removed tmp C:\Users\SEB\AppData\Local\Temp\4276 [exiting]
UnlinkMKV
   removed tmp C:\Users\SEB\AppData\Local\Temp\4656
   created tmp C:\Users\SEB\AppData\Local\Temp\4656
   processing C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_OP_(1008x720_Blu-Ray_FLAC)_[827F1AF5].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_OP_(1008x720_Blu-Ray_FLAC)_[827F1AF5].mkv"
         "C:/Serial Experiments Lain/[Coalgirls]_Serial_Experiments_Lain_OP_(1008x720_Blu-Ray_FLAC)_[827F1AF5].mkv" does not contain segmented chapters
      removed tmp C:\Users\SEB\AppData\Local\Temp\4656
      created tmp C:\Users\SEB\AppData\Local\Temp\4656
   removed tmp C:\Users\SEB\AppData\Local\Temp\4656 [exiting]

**Comment by hilts-vaughan** [comment]
Lain works on my machine. I'm going to look for you. Hold tight, thanks for
the report..

**Comment by sherlockeb** [comment]
It's not just the Lain though, I also tried Kannagi from Coalgirls and Azumanga Daioh from entertheblog

**Comment by hilts-vaughan** [comment]
Understood. Thanks for the report; what operating system?

It's not just the Lain though, I also tried Kannagi from Coalgirls and
Azumanga Daioh from entertheblog

**Comment by sherlockeb** [comment]
Windows 7 Ultimate

**Comment by hilts-vaughan** [comment]
I highly suspect that `mkvinfo` is not installed properly. Are you familiar with the command line? Can you try `mkvinfo` from it and see what it returns?

**Comment by sherlockeb** [comment]
Hi,
Upon checking with command line i found out mkvinfo was broken while mkvmerge and mkvextract were fine so i removed mkvtoolnix and reinstalled it from the links you provided. Doing so fixed the problem. Sorry for taking your time for this and thanks a lot. You were incredebly fast on fixing this issue.
