### ISSUE TITLE
Subtitles broken after unlinking

### ISSUE THREAD

**Issue by jakon2048** [hilts-vaughan/UnlinkMKV-GUI#11]
I'm trying to unlink THORA's Spice and Wolf season 1 as well as Coalgirl's version. I keep hitting this issue: http://pastebin.com/g2d2ZSGk

The subtitles show up, but after the OP, all the styles are messed up. The OP styles are fine. Perhaps this happens because the OP is the first file played?

**Comment by jakon2048** [comment]
I've tried, with the exact same libraries, dependencies, mkvmerge version, etc, on WhyNot's Steins;Gate BD rips. In this, the ordered chapter OP/EDs are "inserted" into the series rather than starting from the beginning or right at the end. The subtitles are styled properly.

Perhaps this is a bug that happens only if the OP is the first file played, before the main file?

**Comment by hilts-vaughan** [comment]
Thank you for your report. I will try it out.

Have you tried other releases? Do they work?

**Comment by jakon2048** [comment]
I've tried 3 releases. Both Thora's and Coalgirl's releases of Spice and Wolf (s1) don't work. They both use ordered chapters and the OP comes right before the show. There's no show then OP then show.

I've tried WhyNot's Steins;Gate. This is more of a traditional ordered chapter thing. There's some show lead in, then an OP, then back to the show. This works. I used the same mkvmerge version and UnlinkMKV-GUI. The only thing that's different in my test are the shows. 

I don't think it's a font issue because the subs shows as if there's no styling associated with them. I think the styles are not being copied properly in the edge case... could you confirm?

**Comment by sherlockeb** [comment]
Hi, I ran into this problem with some of my releases and found some blog post explaining why it's happening and how to fix it, 
http://thisdoesnotcompute.org/2013/01/14/undoing-ordered-chapters-part-2-fixing-broken-subtitles/

Basically unlinkmkv only uses styling from OP subtitles and sometimes that doesn't contain styling for actual episode and that causes the problem. Adding missing styles from episodes subtitle style sheet to OPs subtitle style sheet fixes the problem.

**Comment by hilts-vaughan** [comment]
Cool -- thanks! I'll see if I can include this automatically.

**Comment by jakon2048** [comment]
Perhaps a safer solution would be to merge all the styles from all linked files (OP, actual episode, AND ED) and remove any duplicates. In Thora's Spice and Wolf, the ED's messed up too.

**Comment by hilts-vaughan** [comment]
Great idea. I'll see about including them all. That should fix this

**Comment by jakon2048** [comment]
Thanks for the quick response, but I'm reading the documentation for the original unlinkMKV script: 

`--fix-subtitles        Defaults to on. Sometimes groups don't use uniform subtitle styles and fonts in all segments, it's a good idea to leave this enabled.`

I can't read perl, but it seems like the author of unlinkMKV has accounted for this issue... perhaps there's a bug / edge-case unaccounted for in the current script?

**Comment by hilts-vaughan** [comment]
There should be an option in the UI to enable it. Can you try it with that
option?

**Comment by jakon2048** [comment]
Yeah, I tried it in the original bug submission. It didn't help (plus, it seems like it default are on).

**Comment by jakon2048** [comment]
Sorry to bother again -- any luck? Let me know if there's anything I can help.

**Comment by Elegant996** [comment]
I was just about to report this issue myself. I noticed that you mentioned ChapterUnorderer was inaccurate but it is working in this case. I personally completed a Windows port of this project a few months before you started but I found Perl to be way too frustrating on Windows and pitched it after I noticed these issues.

That could be due to my lack of knowledge with Perl though.

**Comment by jakon2048** [comment]
Fixed in the original UnlinkMKV repo. The original author has done a winport as well.
