### ISSUE TITLE
Output consists of empty MKV containers. 

### ISSUE THREAD

**Issue by charon53** [hilts-vaughan/UnlinkMKV-GUI#12]
I have run into an issue with the unlinker creating empty MKV containers when used on coldhell releases.  I have found this on their release of Kill la Kill and Chuunibyou.  The unlinking process is much faster than it should be, and it produces 5kb files that have nothing in them.  The verbose output can be found at the link below.  Let me know if you need more information.  

http://pastebin.com/G7cEjsSG

**Comment by charon53** [comment]
The way to fix this is to select ignore default flag.

**Comment by jordimra** [comment]
"Default flag" Unchecked: empty MKV containers
"Default flag" Checked: empty folder, no files, nothing...
