### ISSUE TITLE
Can't find Strawberry Perl

### ISSUE THREAD

**Issue by shogunreaper** [hilts-vaughan/UnlinkMKV-GUI#15]
Whenever i try to start the app it just gives me the error "Strawberry Perl was not found. Please include a copy inside your working directory with installed modules. You should have got a copy with this release

I downloaded it from http://strawberryperl.com/releases.html and installed it to C:\Strawberry which was the default.

I even tried moving it to C:\Program Files but it didn't help.

**Comment by hilts-vaughan** [comment]
This will happen when you do not have it in your `PATH` Were you an administrator when you installed this?

Please re-open if you have problems still.
