### ISSUE TITLE
Output Creates Large Pause When Reaching Next Chapter of File on Playback

### ISSUE THREAD

**Issue by ChakaKhan** [hilts-vaughan/UnlinkMKV-GUI#16]
I was successfully able to unlink and output complete files for the anime Bakemonogatari, Tsukimonogatari, and Monogatari Series Second Season. However, when I tried to output files for two other shows in this anime series (Nisemonogatari and Nekomonogatari), there were large pauses almost 30-45 seconds before the file would continue onto the ED portion. What's even weirder was that these pauses make the video player seemingly freeze and the track bar stops moving and any attempt to jump place results in nothing.

I'm currently using VLC ver. 2.2.4 on WIndows 10 64-bit. and all of the files were the 720p versions from Coalgirls's release.

**Comment by ChakaKhan** [comment]
I just noticed that it has been a month since I posted this, so I figured I'd try commenting again for exposure, but also adding a link to the verbose log it produced when unlinking Nisemonogatari 

[Unlink-MKV for Nisemonogatari.txt](https://github.com/hilts-vaughan/UnlinkMKV-GUI/files/379361/Unlink-MKV.for.Nisemonogatari.txt)

**Comment by Shadowghost** [comment]
Problem is also happening with 1080p version. Could be a timecode problem with the MKV itself.

**Comment by ChakaKhan** [comment]
Maybe. I also tried playback using MPC-HC (everything up to date) but that has similar issues too. First, the subtitles are suddenly missing and can't load them despite being selected, but when you get to the ED, the audio continues to play after a 1-2 pause with the video continuing synced up after 4-5 seconds.

If it really is a timecode issue, would I even be able to fix it?

**Comment by Shadowghost** [comment]
Not even sure if it's possible... If I remembered it right best advice over the interent was: Just reencode the source again because everything else isn't worth time and effort.

**Comment by ChakaKhan** [comment]
Welp... I know nothing about encoding stuff ;-; Could I then, in theory, just use some kind of video editor to add the sections onto the main video and adjust as needed? Any good place to start learning?

**Comment by hilts-vaughan** [comment]
This is a weird issue with encoding. Do you still have this problem?

**Comment by ChakaKhan** [comment]
I had actually tried doing it with the 1080p version of the files a few days ago and it ended up working perfectly, so most likely it was the encode

**Comment by hilts-vaughan** [comment]
Cool. I have a new backend for the converter -- would you be interested in testing it for me? It should resolve a lot of these issues.

**Comment by hilts-vaughan** [comment]
Actually, I would like to extend that offer to everyone on this ticket. Please send me an e-mail as listed on my Github profile if you're interested... it should resolve a bunch of these problems and I'd like to get as much confirmation as possible.

**Comment by hilts-vaughan** [comment]
Pre-release version pushed out... hopefully this resolves at least a few issues.
