### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by shogunreaper** [hilts-vaughan/UnlinkMKV-GUI#17]
I'm trying to link Fullmetal Alchemist Brotherhood (atsa release) but when i hit unlink it just returns with the message "The unlinking is complete!" almost instantly but there is no file.

nothing in the output log.

**Comment by hilts-vaughan** [comment]
Hi,

You probably didn't setup the dependencies properly. Did you follow the
setup guide. Including CPAN modules?

If so, please state OS.

**Comment by shogunreaper** [comment]
i have Strawberry Perl, mkvtoolnix ffmpeg and .net installed.

also using windows 7

**Comment by hilts-vaughan** [comment]
Did you follow the part about installing the Perl modules? You can find it
in the README

**Comment by shogunreaper** [comment]
okay i just did that

it created a file this time (only 5kb) but gave me errors

UnlinkMKV
   processing G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_01v2_[BD_720p][AtsA][76A5BD6E].mkv
      checking if file is segmented
         "G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_01v2_[BD_720p][AtsA][76A5BD6E].mkv" contains segmented chapters
      generating chapter file
         loading chapters
            Checking for editions...
            non-default chapter dropped
            Done checking for editions...
         writing chapter temporary file
         looking for segment parts
         checking that all required segments were found
         extracting attachments
         creating splits
         setting parts
         extracting subs
         making substyles unique
         mashing unique substyles to all parts
         remuxing subtitles
         building file
         fixing subs, again... (maybe an mkvmerge issue?)
         moving built file to final destination
UnlinkMKV
   processing G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_ED1v2_Clean_[BD_720p][AtsA][97CB5EEE].mkv
      checking if file is segmented
         "G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_ED1v2_Clean_[BD_720p][AtsA][97CB5EEE].mkv" does not contain segmented chapters
UnlinkMKV
   processing G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_OP1v2_Clean_[BD_720p][AtsA][39C599D1].mkv
      checking if file is segmented
         "G:/Anime/Fullmetal Alchemist Brotherhood/Fullmetal_Alchemist_Brotherhood_OP1v2_Clean_[BD_720p][AtsA][39C599D1].mkv" does not contain segmented chapters

**Comment by hilts-vaughan** [comment]
Hi,

Did you recently just install `mkvtoolnix`? Looks like you're on Windows -- there is a bug with the newest version that prevents it from working with automation (it spawns a GUI by default WTF)

You can try overwriting your copy of winport.pl that came with the release with this version: https://raw.githubusercontent.com/hilts-vaughan/UnlinkMKV-GUI/bbb7e1af9ea39285371a963968a9cad54a977cbe/UnlinkMKV-GUI/UnlinkMKV-GUI/winport.pl

If this fixes it for you, let me know and I can drop a new release. Thanks for the patience.

**Comment by shogunreaper** [comment]
it seems checking ignore default flag allows it to go through.

**Comment by hilts-vaughan** [comment]
Cool -- try the above as well if you have issues. If your files look as expected, please let me know.

Thanks!

**Comment by shogunreaper** [comment]
they seem to work fine.

thanks for your help

**Comment by shogunreaper** [comment]
a sorry one last thing

can you make it so we can change the temp directory?

i have an ssd and don't really like all the writing its doing when i'm putting them on another drive

**Comment by hilts-vaughan** [comment]
I will make an option for it in the interface.

**Comment by hilts-vaughan** [comment]
Please open a seperate issue, though. You can get around this by using a
symbolic link for now. You should note a modern SSD is very durable though,
you likely have nothing to worry about.

**Comment by shogunreaper** [comment]
> You can get around this by using a symbolic link for now.

what is that?

> You should note a modern SSD is very durable though, you likely have nothing to worry about.

yeah but i'd rather avoid writing hundreds of gb at a time to it.

**Comment by shogunreaper** [comment]
> Please open a seperate issue, though.

you want me to open a new topic about it?

**Comment by hilts-vaughan** [comment]
1. yes, open a new topic. This one is closed.
2. Google "junction points". It allows you to move folders to other drives
   without moving them physically, in a sense.
