### ISSUE TITLE
Choose temp directory

### ISSUE THREAD

**Issue by shogunreaper** [hilts-vaughan/UnlinkMKV-GUI#18]
can you allow us to choose a directory on a different drive than C:\

**Comment by hilts-vaughan** [comment]
I'll consider this on a feature request timeline. I'm planning a port using native bindings which would make this a lot easier to support.

**Comment by hilts-vaughan** [comment]
This will be available in the new native port. Simply set your %TEMP% to the proper folder, and then it will be redirected. You can do this as a one-time shortcut if you prefer -- just execute the following in a .BAT if you're on Windows:

```
set TEMP=<YOUR_DIR>
start UnlinkMKV-GUI.exe
```

... and then it will be respected.
