### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by EmpathicIntent** [hilts-vaughan/UnlinkMKV-GUI#19]
I saw the other threads but they didn't seem to have any solutions in them.

As with the other threads, I hit "Unlink", a few seconds pass, and then it says it's complete except nothing has happened. I am using the 64 bit version of Perl, and I have the latest MKVToolnix as well as FFMpeg. I am running Windows 7 64 bit. I also tried installing MKVToolnix 8.xx but it didn't work.

**Comment by hilts-vaughan** [comment]
Hi,

What file(s) are you trying to Unlink? Did you ever get this resolved?

**Comment by hilts-vaughan** [comment]
I'm setting up a new release today, which will include a new "Native Backend" mode which does not require Perl, etc.

You can try this if you're still having trouble.
