### ISSUE TITLE
Input and Output folders on network paths (unmapped networks) are unsupported.

### ISSUE THREAD

**Issue by Yoggedy** [hilts-vaughan/UnlinkMKV-GUI#2]
There's that exact warning below the output log, and every time I try and unlink, it completes the process without doing anything.

Thanks.

EDIT: Forgot to mention, I am running Windows 8. And I tried to get a log, but there's nothing.

**Comment by hilts-vaughan** [comment]
Could you post a log? There'll be a log inside the output window. Or is there none?

**Comment by Yoggedy** [comment]
Nothing whatsoever. It's the strangest thing.

I just press unlink, wait a few moments, and it says it's finished without actually doing anything.

**Comment by hilts-vaughan** [comment]
You installed Perl and all the stuff from the main page?

**Comment by Yoggedy** [comment]
Yup, I followed all the instructions.

**Comment by hilts-vaughan** [comment]
Are you sure the input folder has MKVs in it?

**Comment by Yoggedy** [comment]
Yeah, I'm trying to unlink The Tatami Galaxy.

**Comment by ghost** [comment]
Also having the same issue as Yoggedy.

**Comment by hilts-vaughan** [comment]
Sorry for the long delay @Yoggedy 

Could you try this new release? https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases/tag/0.1.4

**Comment by Yoggedy** [comment]
Oh man, I love you for this, it works!

I can now convert so many more series for my tablet! Thank you so much!

**Comment by hilts-vaughan** [comment]
@Yoggedy Great to hear, if you find any bugs with specific series come back and file a bug and I'll have it fixed faster this time.

Closing this up.
