### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Rait0** [hilts-vaughan/UnlinkMKV-GUI#20]
I am using windows 10 pro x64
I installed everything (x64 and latest ones) 
It still says unlinking completed but nothing is in the output folder..
I am sure that my files are segmented mkvs complete with OPs and EDs. 
I have also tried the new winport. Pl to no avail. 

Please help. 

Ps: if something like this already exists why not a media player for android that can play these type of files (ordered chapters mkv) seemlessly?

**Comment by hilts-vaughan** [comment]
Hi,

Please make sure you have installed all the dependencies in README.MD and provide your operating system and other information.

I've closed this for now since it's old -- but if you still need assistance, please reopen.
