### ISSUE TITLE
UnlinkMKV doesn't detect if files are segmented

### ISSUE THREAD

**Issue by hmdang96** [hilts-vaughan/UnlinkMKV-GUI#26]
Hello, my issue is as stated in the title. I'm using version 0.1.5 as 0.2.1 does not output anything for me. I have Strawberry Perl 5.26.0.1 64-bit, Log4Perl, LibXML, and MKVToolNix v13 64-bit on Windows 10. Here's the verbose output log:

UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\8656
   created tmp C:\Users\Me\AppData\Local\Temp\8656
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_01_(1920x1080_Blu-ray_FLAC)_[5DEC5B88].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_01_(1920x1080_Blu-ray_FLAC)_[5DEC5B88].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_01_(1920x1080_Blu-ray_FLAC)_[5DEC5B88].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\8656
      created tmp C:\Users\Me\AppData\Local\Temp\8656
   removed tmp C:\Users\Me\AppData\Local\Temp\8656 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\5464
   created tmp C:\Users\Me\AppData\Local\Temp\5464
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_02_(1920x1080_Blu-ray_FLAC)_[EF7839D9].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_02_(1920x1080_Blu-ray_FLAC)_[EF7839D9].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_02_(1920x1080_Blu-ray_FLAC)_[EF7839D9].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\5464
      created tmp C:\Users\Me\AppData\Local\Temp\5464
   removed tmp C:\Users\Me\AppData\Local\Temp\5464 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\9352
   created tmp C:\Users\Me\AppData\Local\Temp\9352
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_03_(1920x1080_Blu-ray_FLAC)_[9C0A49B3].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_03_(1920x1080_Blu-ray_FLAC)_[9C0A49B3].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_03_(1920x1080_Blu-ray_FLAC)_[9C0A49B3].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\9352
      created tmp C:\Users\Me\AppData\Local\Temp\9352
   removed tmp C:\Users\Me\AppData\Local\Temp\9352 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\11124
   created tmp C:\Users\Me\AppData\Local\Temp\11124
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_04_(1920x1080_Blu-ray_FLAC)_[31994705].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_04_(1920x1080_Blu-ray_FLAC)_[31994705].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_04_(1920x1080_Blu-ray_FLAC)_[31994705].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\11124
      created tmp C:\Users\Me\AppData\Local\Temp\11124
   removed tmp C:\Users\Me\AppData\Local\Temp\11124 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\8104
   created tmp C:\Users\Me\AppData\Local\Temp\8104
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED1_(1920x1080_Blu-ray_FLAC)_[90375C44].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED1_(1920x1080_Blu-ray_FLAC)_[90375C44].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED1_(1920x1080_Blu-ray_FLAC)_[90375C44].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\8104
      created tmp C:\Users\Me\AppData\Local\Temp\8104
   removed tmp C:\Users\Me\AppData\Local\Temp\8104 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\8196
   created tmp C:\Users\Me\AppData\Local\Temp\8196
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED2_(1920x1080_Blu-ray_FLAC)_[F1A2CF39].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED2_(1920x1080_Blu-ray_FLAC)_[F1A2CF39].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_ED2_(1920x1080_Blu-ray_FLAC)_[F1A2CF39].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\8196
      created tmp C:\Users\Me\AppData\Local\Temp\8196
   removed tmp C:\Users\Me\AppData\Local\Temp\8196 [exiting]
UnlinkMKV
   removed tmp C:\Users\Me\AppData\Local\Temp\10160
   created tmp C:\Users\Me\AppData\Local\Temp\10160
   processing C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_OP_(1920x1080_Blu-ray_FLAC)_[7F7E706B].mkv
      checking if file is segmented
         sys > mkvextract chapters "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_OP_(1920x1080_Blu-ray_FLAC)_[7F7E706B].mkv"
         "C:/Users/Me/Downloads/Video/Nekomonogatari/[Coalgirls]_Nekomonogatari_OP_(1920x1080_Blu-ray_FLAC)_[7F7E706B].mkv" does not contain segmented chapters
      removed tmp C:\Users\Me\AppData\Local\Temp\10160
      created tmp C:\Users\Me\AppData\Local\Temp\10160
   removed tmp C:\Users\Me\AppData\Local\Temp\10160 [exiting]

Is this a problem with the files themselves? They clearly are segmented, as the OP and ED won't show if their files are missing. Any input is appreciated.

**Comment by hmdang96** [comment]
Issue solved after downloading a new zip file of the program

**Comment by hilts-vaughan** [comment]
Great! Let me know if you have any other problems.
