### ISSUE TITLE
"The Unlinking is Complete!", with no output

### ISSUE THREAD

**Issue by davidlohle** [hilts-vaughan/UnlinkMKV-GUI#3]
Environment is Windows 8.1, 64bit install with mkvtoolnix installed as 64bit as well. Using Strawberry Perl (v5.22.0, 64bit), as well as Log::Log4perl (1.46) installed.

Nothing displays in the Output Log, and a toggle of various combinations of options still does not fix it.

How should I go about debugging this? I've tried multiple different shows.

**Comment by hilts-vaughan** [comment]
Are you running a release ZIP from the page? You can try running the Perl
script manually from the directory and see if it outputs anything

**Comment by davidlohle** [comment]
Nope, it's uncompressed. Running the script from the Perl console returns:

```
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at C:\Users\David\Desktop\winport.pl line 352.
```

**Comment by hilts-vaughan** [comment]
This will happen if the "input" folder has no MKVs inside of it. Are you
sure input has MKVs in it?

**Comment by davidlohle** [comment]
Yup, I'm using a batch of .mkv's with external OP/EDs.

**Comment by hilts-vaughan** [comment]
Could you share a screenshot of your user interface? It would help, I'll
investigate for you.

**Comment by davidlohle** [comment]
Thanks!
![captur2e](https://cloud.githubusercontent.com/assets/2215601/8026823/0bd9a60c-0d56-11e5-828f-0db122d85d68.PNG)

**Comment by ghost** [comment]
I'm also having the issue Proplex is having.

**Comment by hilts-vaughan** [comment]
Please try this new release: https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases/tag/0.1.4

And let me know how it works for you.

**Comment by davidlohle** [comment]
Works beautifully now, thank you!

**Comment by hilts-vaughan** [comment]
Great, glad to hear @Proplex 

Closing this up. If you find any bugs with specific series, please open an issue.
