### ISSUE TITLE
Output quality of linked files

### ISSUE THREAD

**Issue by wanderingotaku** [hilts-vaughan/UnlinkMKV-GUI#5]
I am trying to link together an anime opening and ending to a series. The program works correctly, however the output file has quality issues. I have installed all the files (even ffmpeg after having this issue in the beginning) but the issue still permits.

What happens is, the video plays fine until it gets to the opening. The sound continues to play, while the video freezes. Part of the subtitles play but then freeze as well. When it gets to the end of the opening, the video plays fine again. This repeats in the ending. After the ending is a "next time on" and it plays fine.

I have the verbose log for it. As the log is long I have provided a pastbein since it is a long one.

http://pastebin.com/Vayrmmtt

One thing that I just thought of is I had changed the file names. I changed them back to the originals, and the exact same thing happened. Didn't really expect that to be the issue but thought I would try.

**Comment by hilts-vaughan** [comment]
Could you try in another player? What video player is having issues?

**Comment by wanderingotaku** [comment]
I tried VLC and the Video app in windows 8 before posting, and got the exact same result. I just tried in Windows Media Player and Media Player classic and get the same result. I don't believe this is a video player issue, rather than a file issue, since multiple players result in the same issue.

For reference, I am trying to combine a show called Casshern Sins, by THORAnime, using episode 6 (for no reason other than I chose it.)

**Comment by hilts-vaughan** [comment]
Thanks for the report. Did you test anything else? Do they work? I'll check out this particular instance..

**Comment by wanderingotaku** [comment]
I did test others. This time I tried Turn A Gundam from Encodergasm, and Eden of the East from THORAnime.

For Gundam I did both Episode 2 and 40 (they each have different opening and endings.)

Ep 2: http://pastebin.com/P6Et4GKJ
The opening worked perfectly, but the ending encoded with terrible video artifacts. The video does move, and the subtitles run fine, but the video is messed up to where all you see is green and a little bit of other color.

Ep 40:http://pastebin.com/y8Zx2JUL
I got a much better result on this episode. The opening and ending encoded perfectly, and the video quality was unchanged.

The results got me curious so I tried at random episode 7, which has the same opening and ending as 2. It resulted in the same issue as 2. However I also noticed that the actual episode became stuttered. The animation in the episode was fluid before. I checked the original and it was fine. It also didn't happen on episode 2 and 40. Just to be sure, I re-tested unlinking episode 7 from fresh files and got the same result.

For Eden of the East Id id Episode 1 and 8.

Episode 1 encoded perfectly.

Episode 8: http://pastebin.com/9Pj5FJnX
The opening and ending encoded fine. The rest of the episode encoded very poorly, with artifacts everywhere making it unwatchable.

Finally I tested all the episodes with issues in alternate viewers, and I got almost all the exact same issues per episode. The only different result was that Turn A Gundam episode 7 wasn't choppy in playing the video. However all other issues remained.

So hopefully these results help. I can't find any other shows right now that I have with the opening and ending split. I guess that's a good thing.

**Comment by hilts-vaughan** [comment]
Are these all Thora releases?

EDIT: Nevermind, saw you mentioned Encodergasm. I've primairly tested on Coalgirl's. Let's see here...

**Comment by wanderingotaku** [comment]
(oops didnt mean to hit close instead of comment.)

Yeah Encodergasm was for Gundam. It does seem THORA has a running theme. If I find others in my library that aren't THORA I'll give them a test.

**Comment by hilts-vaughan** [comment]
Hi @wanderingotaku 

Could I bother you? I released a new version today @ https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases/tag/0.1.5

Someone else found a bug in the handling of the XML afterwards. I believe it may resolve your issue on some releases. Thanks!

**Comment by wanderingotaku** [comment]
Thanks. I downloaded the new release and tested each of the ones I had problems with before. Each one had the exact same resolution unfortunately.

Here is the last output for Tun a Gundam 7 if it helps. I didn't grab any of the others.
http://pastebin.com/mMsdJTJ4

And for the sake of trying, I tried one from the original show with this problem Casshern Sins. I used episode 14 and I got a completely perfect encode.

http://pastebin.com/3UC0zRD8

So I don't know what to think. I'm going to try and start from the beginning of these series and see what output I get as I go one by one.

**Comment by hilts-vaughan** [comment]
So in other words, some of them are working now and others are not?

**Comment by secondsabre** [comment]
I'm seeing similar things (green/grey screen, highly corrupted video) on the majority of a series I'm trying to do, ZZ Gundam [EG].  A few files came out fine, but most of them have major video problems in one or more of the segments.

I've run into weird corruption errors with certain files using Handbrake before, and what sometimes works for that is to just re-run the video through MKVtoolnix. Tried that here (re-packaging the OP/ED/Ep, re-inserting the UID's from the original files), but still had the exact same problem with each video.  It feels like maybe some kind of flag dealy making ffmpeg puke, especially since a few of the videos worked just fine, but I can't find any evidence in the UnlinkMKV logs or the MKVinfo for the working and non-working videos.

Here's a log for two episodes, both with the same problem.OP and ED (originally segmented) play fine, main EP video is just green and gray the whole way through.  The segments have all been re-muxed through makeMKV to standardize flags (if any).

http://pastebin.com/cQz1HnH8

Tried with all the various flags, and multiple video players, of course.  I hope some of this helps in some way.

**Comment by hilts-vaughan** [comment]
Thanks for the report. Seems like it's happening frequently for a few
users. I'm going to grab some of these releases this weekend and try and
clean it up.

Subscribe to this issue and I'll get back to you guys!

Thanks for taking the time to write reports.

**Comment by secondsabre** [comment]
Er, sorry.  It seems like my particular issue might actually be more related to #9 , but I feel like it also might all be part of the same problem.  I also went in and checked the TEMP files, particularly the split-001.mkv and split-002.mkv, and they both seem fine, so I'm pretty sure it's something in the rebuild process that's breaking.

Also, it seems that in the completed files that are broken at least one of the segments is always fine, although whether it's the OP, ED, or EP seems to vary.

**Comment by wanderingotaku** [comment]
"Er, sorry. It seems like my particular issue might actually be more related to #9 , but I feel like it also might all be part of the same problem."

I would say they are similar if not the same. I got a green screen on my most recent test (though not since august, been busy.) Hopefully hilts-vaughan has a solution, but in the meantime I am waiting patiently :D

**Comment by hilts-vaughan** [comment]
I have a good idea of where this is coming from now. Just need a bit of
time. :)

**Comment by Coveka** [comment]
Sorry to bug you, but have you found a fix yet?

**Comment by Nireth** [comment]
Also wondering if there has been any progress. I've just had the green squares issue on the [Coalgirls] K-ON! Tried on 3 devices and the issue is present in different forms (sometimes grey, sometimes green). Interestingly, PLEX can play [FFF] videos fine even though they also segment their openings/endings. 

Edit: Another interesting point is that it only happened with the first opening/ending. The second opening worked perfectly fine, as did the ending even though it's the same file.

**Comment by hilts-vaughan** [comment]
FF does not segment their files, they only provide the OP and ED as seperate files if you want them.

I've found a fix for most of these files now.

**Comment by hilts-vaughan** [comment]
I'm releasing a new version today with a newer backend, if you still have issue you should try this out and if not, each open a ticket with the release(s) you're having issues with so it can be investigated.

Thanks!
