### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by ghost** [hilts-vaughan/UnlinkMKV-GUI#6]
So I have installed Strawberry Perl (64-bit), logging module, and the XML module for it, as well as the latest MKVToolnix (64-bit). I ran UnlinkMKV-GUI as administrator, chose the path to CoalGirls's Nisemonogatari release, chose the output folder, hit 'Unlink' and about 15 seconds later I get the 'The unlinking is complete' dialog and that's it.
No output files can be found, which is no surprise - it took to little time to finish this. 
Anyway, I tried it with CGi's Nichijou release, using different folders, older MKVToolnix versions - no result.

The log only says:
UnlinkMKV
UnlinkMKV
...
and so on.

Am I doing it wrong or something?
Thank you

**Comment by hilts-vaughan** [comment]
Could you attach a verbose log?

**Comment by ghost** [comment]
Well, like I said It just says
UnlinkMKV...

![ss 2015-07-21 at 12 59 43](https://cloud.githubusercontent.com/assets/13418097/8778912/cb6750c8-2f43-11e5-9469-ea0a4711c660.png)

I read another issue thread and checked If I have mkvextract in variables - I didn't have it.
Now I fixed that and the problem is still there. 
![ss 2015-07-21 at 01 04 00](https://cloud.githubusercontent.com/assets/13418097/8779081/c07008b2-2f44-11e5-83b6-7502eb85b81a.png)
I also checked If I have logging module installed correctly - it says that the module is up to date.

**Comment by arminmacx** [comment]
Hi

i download all dependency for your app but i got no output. it just take a second and it shows "the unlinking completed" but there are no output. i don't even get any verbose when i selected from main view.

**Comment by Ession** [comment]
I get the same (or rather lack thereof). Ticking options changes nothing.
Verbose output or not, the output log (and folder) remains completely empty.

**Comment by NeroAurea** [comment]
Hi, 
I Have the same issue and for me it was when trying to merge a coalgirls download of Nichijou, and I cant help but wonder if it has anything to do with the fact that the openings and endings are not the first and last things, but are instead buried inside the main show. I am also having trouble just trying to manually merge files with MKVtoolnix using the append function and the mkvtool-gui. I have successfully done some other simple things like add separate subtitle files, but I don't really have a clue what I'm doing, so it might just be that I'm being completely incompetent.

**Comment by hilts-vaughan** [comment]
There's a new native release coming out today or tomorrow. Please try that one and let me know if you have the same problem. :)
