### ISSUE TITLE
Chapter .xml files retain <EditionFlagOrdered> property

### ISSUE THREAD

**Issue by StevenFoster** [hilts-vaughan/UnlinkMKV-GUI#7]
Hi there.

First of all I just want to say thank you so much for this tool. I have found it invaluable in sorting out pesky ordered releases.

One thing I noticed when using it on some releases was that, whilst it re-assembled everything into one file correctly, playing it in MPC-HC exhibited some strange behavior when changing chapters (which would previously have been the point where it would load the next segment). You would sometimes end up with subtitles showing twice just before the end of the chapter, and when it moved on to the next chapter, the last couple of seconds of the previous one would show again very quickly, like super sped up. Bit hard to explain but it looked weird.

Anyway, I noticed that this behaviour went away after editing the chapter .xml file and removing the following line:

```
<EditionFlagOrdered>1</EditionFlagOrdered>
```

Presumably it's safe to remove this line anyway as it is no longer an ordered release, and doing so seemed to fix the weird issues MPC was having. Would it be worth making sure this flag is not included/stripped out as part of the unlink process?

**Comment by hilts-vaughan** [comment]
Yes, thank you very much. If you want to submit a PR if you write Perl, I
can merge it. Otherwise, I will make the change and credit you.

Thanks for your kind words!

**Comment by StevenFoster** [comment]
Okay, I **think** I've done it right! If not, sorry!

https://github.com/hilts-vaughan/UnlinkMKV-GUI/pull/8

**Comment by hilts-vaughan** [comment]
For everyone reading this, the newest release _SHOULD_ have this issue fixed. 

https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases/tag/0.1.5

Thanks @StevenFoster
